FORMAT: 1A
HOST: http://localhost:3030/

# arij

Arij's project API

# Users API

Resources related to users

## User Collection [/api/users]

### List All Users [GET]
Roles: **[admin]**

+ Response 200 (application/json)

        [
            {
                "_id": "5895adafa179991ac84e7793",
                "nickName": "azaliasz",
                "name": "admin",
                "email": "admin@a.pl",
                "created_at": "2017-02-04T10:59:43.684Z",
                "updated_at": "2017-02-04T10:59:43.684Z",
                "projects": [],
                "roles": [
                  "admin",
                  "user"
                ]
              }
        ]

+ Response 500 (application/json)
    
        {
            "errorMsg": "Getting users failed"
        }


## User [/api/users/{user_id}]        
+ Parameters
    + user_id (String) - ID of the User in the form of an ObjectID
    

### Add New User [POST]
Roles: **[admin]**

+ Request (application/json)

        {
          "nickName": "testUser",
          "name": "test user",
          "email": "test@a.pl",
          "password": "secretHashedPassword",
          "projects" : [],
          "roles": [
            "user"
          ],
          "active": true
        }

+ Response 200 (application/json)

        {
          "__v": 0,
          "_id": "589753f61f379020cabe634c",
          "nickName": "testUser",
          "name": "test user",
          "email": "ttttt@a.pl",
          "created_at": "2017-02-04T10:59:43.684Z",
          "updated_at": "2017-02-05T16:33:58.129Z",
          "roles": [
            "user"
          ],
          "active": true
        }
        
        
+ Response 500 (application/json)
    
        {
            "errorMsg": "Adding user failed"
        }

    
### Get User Details [GET]
Roles: **[admin, user]**

+ Response 200 (application/json)

        [
           {
              "_id": "5895adafa179991ac84e7793",
              "nickName": "azaliasz",
              "name": "admin",
              "email": "admin@a.pl",
              "created_at": "2017-02-04T10:59:43.684Z",
              "updated_at": "2017-02-04T10:59:43.684Z",
              "roles": [
                "admin",
                "user"
              ],
              "active": true
            }
        ]
        
+ Response 500 (application/json)
    
        {
            "errorMsg": "Getting user failed"
        }

### Deactivate User [DELETE]
Roles: **[admin]**

+ Response 200

+ Response 500 (application/json)
    
        {
            "errorMsg": "Deactivating user failed"
        }

### Change User [PUT]
Roles: **[admin]**


+ Request (application/json)

            {
                "nickName": "azaliasz",
                "name": "admin",
                "email": "admin@a.pl",
                "projects": [],
                "roles": [
                  "admin",
                  "user"
                ]
             }
        
+ Response 200


+ Response 500 (application/json)


### Change User Properties [PATCH]
Roles: **[user]**

Properties of body object are optional.
+ Request (application/merge-patch+json)

        { 
          "nickName": "New Nickname Value",
          "password": "new password value"
        }
        
+ Response 200


+ Response 500 (application/json)