FORMAT: 1A
HOST: http://localhost:3030/

# arij

Arij's project API

## Users collection [/api/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "_id":"1",
                "name":"admin",
                "email":"admin@a.pl",
                "password":"9Rq2COxIx5Y2FUGd",
                "created_at":"2016-11-26T09:36:50.655Z",
                "updated_at":"2016-11-26T09:36:50.655Z",
                "roles":["admin"],
                "active":true
            }
        ]

### Create a New User [POST]

+ Request (application/json)

        {
         
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
               
            }