module.exports = {
  ADD_PROJECT_REQUEST: 'ADD_PROJECT_REQUEST',
  ADD_PROJECT_REQUEST_SUCCESS: 'ADD_PROJECT_REQUEST_SUCCESS',
  ADD_PROJECT_REQUEST_FAILURE: 'ADD_PROJECT_REQUEST_FAILURE',
  GET_ALL_PROJECT_REQUEST: 'GET_ALL_PROJECT_REQUEST',
  GET_ALL_PROJECT_REQUEST_SUCCESS: 'GET_ALL_PROJECT_REQUEST_SUCCESS',
  GET_ALL_PROJECT_REQUEST_FAILURE: 'GET_ALL_PROJECT_REQUEST_FAILURE',
  PROJECT_NAME_CHANGED: 'PROJECT_NAME_CHANGED',
  PROJECT_SHORTCUT_CHANGED: 'PROJECT_SHORTCUT_CHANGED',
  PROJECT_LEADER_CHANGED: 'PROJECT_LEADER_CHANGED'
}

