export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_REQUEST_SUCCESS = "ADD_PROJECT_REQUEST_SUCCESS";
export const ADD_PROJECT_REQUEST_FAILURE = "ADD_PROJECT_REQUEST_FAILURE";
export const GET_ALL_PROJECT_REQUEST = "GET_ALL_PROJECT_REQUEST";
export const GET_ALL_PROJECT_REQUEST_SUCCESS = "GET_ALL_PROJECT_REQUEST_SUCCESS";
export const GET_ALL_PROJECT_REQUEST_FAILURE = "GET_ALL_PROJECT_REQUEST_FAILURE";
export const PROJECT_NAME_CHANGED = "PROJECT_NAME_CHANGED";
