export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_REQUEST_SUCCESS = "GET_ALL_USER_REQUEST_SUCCESS";
export const GET_ALL_USER_REQUEST_FAILURE = "GET_ALL_USER_REQUEST_FAILURE";
