module.exports = {
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_REQUEST_SUCCESS: "ADD_USER_REQUEST_SUCCESS",
  ADD_USER_REQUEST_FAILURE: "ADD_USER_REQUEST_FAILURE",
  VALIDATE_USER: "VALIDATE_USER",
  VALIDATE_USER_EDIT: "VALIDATE_USER_EDIT",
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_REQUEST_SUCCESS: "GET_USER_REQUEST_SUCCESS",
  GET_USER_REQUEST_FAILURE: "GET_USER_REQUEST_FAILURE",
  USER_NAME_CHANGED: "USER_NAME_CHANGED",
  USER_EMAIL_CHANGED: "USER_EMAIL_CHANGED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  USER_PASSWORD_CONFIRM_CHANGED: "USER_PASSWORD_CONFIRM_CHANGED",
  INITIALIZE_NEW_USER: "INITIALIZE_NEW_USER",
  MODIFY_USER_REQUEST: "MODIFY_USER_REQUEST",
  MODIFY_USER_REQUEST_SUCCESS: "MODIFY_USER_REQUEST_SUCCESS",
  MODIFY_USER_REQUEST_FAILURE: "MODIFY_USER_REQUEST_FAILURE"
};
